# Generated by Django 3.2.13 on 2022-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='店名')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
            ],
        ),
    ]
