# Generated by Django 3.2.13 on 2022-04-22 00:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.shop', verbose_name='対象店舗')),
            ],
        ),
    ]
