# Generated by Django 3.2.10 on 2022-04-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='投稿した人のIPアドレス'),
            preserve_default=False,
        ),
    ]
