# Generated by Django 3.2.10 on 2022-05-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_review_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bbs/review/image/', verbose_name='画像'),
        ),
    ]
